#!/bin/sh
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mail-user tamara.prieto.fernandez@gmail.com
#SBATCH --mail-type FAIL
#SBATCH --cpus-per-task 1
#SBATCH -t 10:00:00
#SBATCH --mem 30G

source ReadConfig.sh $1
DEPTH=$2
size=$3
DATASET=Wang.${DEPTH}.${size}

module purge
module load gcccore/6.4.0 bedtools/2.27.1
mkdir -p $POSADALAB/APPS/ginkgo/uploads/${DATASET}

while read SAMPLE
do
bamToBed -i ${WORKDIR}/${SAMPLE}.${DEPTH}X.filtered.bam | \
	gzip > $POSADALAB/APPS/ginkgo/uploads/${DATASET}/${SAMPLE}.${DEPTH}.bed.gz
done < ${ORIDIR}/${SAMPLELIST}


cd $POSADALAB/APPS/ginkgo/uploads/${DATASET}
ls *.bed.gz > list
# Create configuration file and modify parameters
rm config
echo "init=1" > config
echo "process=1" >> config
echo "fix=0" >> config
echo "segMeth=0" >> config
echo "chosen_genome=hg19" >> config
echo "rmpseudoautosomal=0" >> config
echo "binMeth=variable_"${size}"_150_bwa" >> config
echo "rmbadbins=0" >> config
echo "b=0" >> config
echo "f=0" >> config
echo "distMeth=euclidean" >> config
echo "clustMeth=ward.D2" >> config
echo "sex=1" >> config
echo "q=0" >> config
echo "color=3" >> config

module purge
module load gcccore/6.4.0 php/7.2.12
module load gcc/6.4.0 R/3.5.1
bash $POSADALAB/APPS/ginkgo/scripts/analyze.sh ${DATASET}

# From the data file generated by ginkgo we can get the MAD values using an R script 
# https://github.com/robertaboukhalil/ginkgo/issues/17
# GinkgoMAD.sh
